@CodeDesignPlus.Net.Microservice_HostAddress = http://localhost:5175

GET {{CodeDesignPlus.Net.Microservice_HostAddress}}/todos/
Accept: application/json

###

GET {{CodeDesignPlus.Net.Microservice_HostAddress}}/todos/1
Accept: application/json

###
