global using CodeDesignPlus.Net.Exceptions;
global using CodeDesignPlus.Net.Microservice.Rest.Core.Mapster;
global using CodeDesignPlus.Net.Microservice.Rest.Core.MediatR;
global using CodeDesignPlus.Net.Microservice.Rest.Core.Middlewares;
global using FluentValidation;
global using FluentValidation.Results;
global using Mapster;
global using MapsterMapper;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Moq;
global using System;
global using System.Collections.Generic;
global using System.Net;
global using System.Threading;
global using System.Threading.Tasks;
global using Xunit;
global using C = CodeDesignPlus.Net.Core.Abstractions.Models.Criteria;
