name: Build and Push Container Image

on:
  push:
    branches:
      - main
      - rc
      - dev
      - feature/*

jobs:
  ci:
    uses: codedesignplus/workflows/.github/workflows/container-image.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice
      microservice-name: ms-archetype